language: bash
services: docker
before_script:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart
script:
- docker build --squash -t mydatakeeper/drone-aarch64-makepkg .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/drone-aarch64-makepkg
  on:
    branch: master
env:
  global:
  - secure: c4S8Zh8Hw1PIQr55X2LR1b/AFOh6KhTS7lvZ6oNGGqUMtgY5RRKvXJDUpojkRWMSAKCerGp4tp44CAz8Oa4iviBQFe7COWpbmKyYp07vsPQ7M7xG3jztXDf4ueVtS/Nd32E1T3i3/C61pSlZWpI1VQ1Aa4aXyyU9NFjGaUpQVKJ513wwjwaJEDA2FKBupukwjGHTanP0n0zltDXjbLSWplshdfmk8SMHjXebFkdEjJnMQvBjvcOdRw1GZ/5gf3FUtTNEBHf/favTBCTpvE0ledl5jTRbYDs3pUwDN1OyP+s0VXAa3cGDnhD7mNUvTZiqzQ2iwvzZPD57hsltAhQhIjX4zwBRX2lrBn6A0TFtksI2jtagUzD3MMjS3458PVUEXH2njz12rVgbIKO2MKDZnHL1elBqeR47DjU4XuWZ951ZXX+o2hGAVFtQr4mMPZ9eZlA7cL6S6EKVfkyEsKtZI2dFQYFbujJiTC90ogATnZZX5Sqg3H2rD5XpnxXlMcxev6Eq7yv0l2YRSuWN15G6hRvZJnCdnUUG+YF/ElFvMFsnL7UFqm59vvJD/3G/0fvE83oKSv7JDNjrIHypX3hIERPAI0Wd5cYT2ldoM9btJyTJ6Nh93R/hMsXXMmZ/hZV50/SHWmYxmQD6KnztqkzsIavnvxTd5SThxu9oqDw6o54=
  - secure: QikhQFcL7pJMAz1a3m2+8dnEhWx/y7cYsibfeK8pKGj3P1+H8iId0BCkOFl6ZNincJjMwh53oaEcqT62tEeNtXgtItBXTR7ETt3hwI5a5GX34ycUngB3ayzSqh4reO9tdEXUZqeoaTndTmYFyIhN540t/mIwmxBIKpUvcqLHyJSISRJC5Edsqny6ybitLVGzQfpXGh46mY+T8tMiymUPIM+KN1p0Em86OzHVytxE3akcl5KPk0ov6FHZot9WeSbTRMCE8w9MpfvPnLGTyJqKOmd4dixZmSbjhm8Q7iQoi91su3Nlr7V3n12q2/SOGzTxWRJsM8Ed+vyMUuGZOCHFhbSvOr2pBrQ0F5ErdckoZdSH/vOahIZmWmYoUAdyWiY9ljFmaaq2B6wGqe3KeH1nsiJ5QPs1gsSqhkijwnJ7sUQ3+5EWLakvZjGL23fHseGzpQb0+fXFSp177qNRQBCDqX4iTBuI9a3BvZSsAChKsu503se9RivUb+2GrPlYAioPfbySShLL1uKteHYQBOZqdDBgyBFwXv9SsFtnM+JE/8dr5Hzok06YTcUzkS/JOeMXpNNSd+TGocmqiHMhaGLdY86Uv4b+V8WdLqf0NIrCafXP90wOd3vMIn0fs67RrU9TxtFAfkDfCfHYkX9x7AGX+zu8Twb70VQ+1Vm7OfwOhyE=
