language: bash
services: docker
addons:
  apt:
    packages:
    - qemu-user-static
before_install:
- sudo update-binfmts --enable qemu-aarch64
before_script:
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz.md5
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz.sig
- md5sum -c ArchLinuxARM-aarch64-latest.tar.gz.md5
- gpg --recv-keys 68B3537F39A313B3E574D06777193F152BDBE6A6
- gpg --verify ArchLinuxARM-aarch64-latest.tar.gz.sig ArchLinuxARM-aarch64-latest.tar.gz
- wget -nv https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-aarch64-static
  -O qemu-aarch64-static
- chmod +x qemu-aarch64-static
script:
- docker build -t mydatakeeper/drone-aarch64-makepkg .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/drone-aarch64-makepkg
  on:
    branch: master
env:
  global:
  - secure: vE6obCk77A6OtWJIM+g7DKCbYE43pmbLzjDEiH8yjQzBqIsz/9LC1kgy+3CQ+eWcVnWq+wn30UH+MOlCc05uzpoR+hl6jjeCwr3UHBIMOBsC/Fjrg3vdtsPk4MkeSr3EL2uf42P9dsCaFMilaZk3IaqKnt6uLXoRwMClIARW7VG0OOpsJy0Ik4rMYZo+GhGh3HmSdVYzAdIhlixdmj9TGJ+q5TF9PtmzxZHfYUM3uDrTzPofQ1FINfDxZ8x+fi3qBULBunV1MbPQm+Xx3uC9rJOiOrEiOnI9pzN1+RfJ2Hhb+Ey9b+Gk8genVaX/Lc7auFuUYi9DvpXFDDbAY4OPLPVGpze0D2CZ+ZDLsP1HSBxzaXqacaFwV5KO9eep4tqkH6gJ8+mYj62vrAZHhhfn3ZYNUYHgzcnfzqmc/SWPLmYaYY6xBR1P4BGc0lsSisSYHnuv4Qv+kCuhbHdeb0dpGil6kFinpWes0MqNfPci0z/Ywn9XhAaKspSeDVovnnPgC+YzrqjGNWY7f+rgmCGwJWW01IOvxdVAFr7DUET9YjJiFCKmPJVBa8KD/87ACkgkw+gmrU5lJO390P1kAPB2SvKalu4BQgd6UqAaFNYkAbbNVTbW7rKmtLOGbOm8bnv9Ma65E9cN8aEBuSVhBEWw/RfsGIfcgb2zCcZa7LZshYQ=
  - secure: EgoXmlQVvGzJvgbv6CDFtKkFKMqedw+dMjBbU0XH08HEQu59ygUWS5sYgPbPPrCssDuj8OpqOCQc4QrhSk9dV54FPwXAdVt5E7kzC1gyw/LKjLyCpkdPetwDK93r59GNCGy9aSkVv4JfuUwX4PSDgJ7lg/GwCh4ZsXTRuhk/r+Nqdyi7GdsTYSIDi0EiKbGDlQOu4icX24SUASV9ikPeikFx+gZ3s8AxtrsJgnD58vVb/yo9IjDIpaETxn915ciGBFvFhZqLEmCM9AKdIKVUBINohXyB130hDwAsZGeiRfePnPFmDDfReBjCJmrvC4i/taewO3U9ZuZtsZtHBe+hVt6JRf+/8iw7aQTE12ywTLTHXMGdyW91U/DnlNXhyYNUGgJRcahWr0OIpLrRtFf9EAw14ZfRSHykHQrtxHniJYYtA3i7GVLnrFX+51zYZjeyy3RU9YYzXPvxERQ28DdIoFVJ6yApXPcsbFbIrpdsODvacJI9D29PS6Niq7vscndCH6P5q1j4s1onesayp6FguhNyniYiGLMQ/eD5mRyLrCvfV6WrzXL+xF4EnUQvgZYRpJw1SocRLfBVqMCBizSxe1Q4sZltkviebs40BAnseBh8HUyEcTx3XHweE++G9m/EoS5Yl/u64xVSL74i8LJ7pMsgW3AboI+nuLw57rUvmPA=
