language: bash
services: docker
before_script:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart
script:
- docker build --squash -t mydatakeeper/drone-aarch64-makepkg .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/drone-aarch64-makepkg
  on:
    branch: master
env:
  global:
  - secure: FB6ViACEJ6cAV6fh3TJKtnpt2iFWzzFl4cBrHxme05wtTgken/zTlAjrCrnMhCmW7/+kwsxYq8YozaLdhgQOTQmhha+u7241F7dFlEbrqPyZ7+HemQH2U4wW8soTOW7YrcwVoVRYS07/EA8s6vPoiXJdSoIOtwUIJzF17ZOrqlV5klYsEGpzGLv9nj+ota8vPRQDe+RPxx0hR9ju5qdz8tdmvKeAfDcouykFZtYZdAzTRR+0pgi1776KiMEAGE9xV2CMDQxeyK+9eOpEfZ8jAK4cXUUnUEAxvPrs4pu1T5nwLjP28OniKPFjz1/5qyWLOXdvKCMZpQLEJHvM64QqslqWDpamixmS4sPi44x7Ga6IrRZrscN+ds7fspBX/+q31EBLxh5bonUDPuCb+9c9ZfJuPGZJ24/jt41UI491rA42q3X5uaJC/bWP1ZNFKxu6buxnjoWbS3w1yoOdfjrJF9EDczUsoZeyXr81ZEXKOQU4I+zDzVql50qxbENOHwkATvabRH4iWsGFK1wmvb0NAovStx5UErOYdDCrP2BAvZP50d21c9O0pHL7UyyRJkBJl4p3Zmd63oe6g3Ci7UYufip/F3hBInUtxaJuEstbKawwOpwqQs/bpgZ+YGIuJq9kuf9g0YpIBah56UHG9d5hciQ8XqFNcjvefsyB9xsnpU0=
  - secure: rhty1Vc9zvAOQLJ4E/LkQ0m8P+Cc/Kf+m65KOb5cPGKmKc/fF7DBEZ6py4NaJXn0nvvI1LKM9IyvP+uWgeusQ9EzMSThCebeaplfD8Gu6mRqoKldDvxHy77cCBTrONf7llN1mYmDvYG+N36us88577+hBgBynJaa7Lnbxvmgff9y0blt3VoJKJz/9qs+EVAaSTHxFaw6Mydy9w2Z0K7CB4aK3uouV4Mn5MsKkqPrQgvnz/0XO/ETPU7RBveDD/ZIwXj2TmM1TsTLdLxKK3QUO+3VL32LJuN+8iZTD0XtT5SQ3CNAzwDMNaS7Swju7nZVCDY34lXrU71alMveG1Wd6cRbt+Su0zvITciMx0s+pmPoEAWQTUaYEFaZ1ElUwFuDsonQYQypEli4wFxCBV7GuD6MFMD7ee9azHz3S/p6QNLHGOdFlYwXcJz5PzrRgjlWswp5fbdtEmMghBqwXifnT1TPX+CIMzwEFf+G8VJq90aC+MMMVJjuJqTGRQQ3ro07I4rHfqxs4KSpOU0WhV5JsDeaVNRvNeTwRSCyhr8N8Cb+0mJZ8Ugm8qkNCAUd2mmQTgIfo/XlHGMY9j0G77bshDOVZuMsLzSwoUNcYh18uVYtvh7OeRl5pCMfPk+Gn6Z8tARY40faq7304+92N0sGB/aS7zxVbgPFO9lEy1ekyZ4=
